### ISSUE TITLE
Indexer les données

### ISSUE THREAD

**Issue by DevHugo** [DevHugo/zds-site#6]
- [X] Indexer les différentes données
- [ ] QA

**Comment by artragis** [comment]
est-ce que le "needQA" consiste simplement à envoyer le rebuild index ou bien faut-il s'assurer d'avoir une base neuve avant?

**Comment by DevHugo** [comment]
T'embete pas pour l'instant à faire la QA, le code va encore trop bouger, c'est juste pour marquer que j'avais bien avancé et qu'il resterait plus qu'a tester.
